import 'package:flutter/material.dart';

class AppConstants {
  static const String appName = 'Clear Bill';
  static const String appDescription = 'GST Invoice Manager App';
  static const String appTagline = 'Bill Karo, Smart Karo';
  static const String appVersion = '1.0.0';
  static const String packageName = 'com.subhaworld.clearbill';

  static const Color primaryColor = Color(0xFF1D9E75);
  static const Color secondaryColor = Color(0xFF0F6E56);
  static const Color accentColor = Color(0xFFFAC775);

  static const int freeInvoiceLimit = 10;
  static const int freeClientLimit = 5;
  static const int freeProductLimit = 10;
  static const double premiumPrice = 299.0;

  static const String pdfFooterText =
      'Generated by Clear Bill - GST Invoice Manager App';
  static const String playStoreUrl =
      'https://play.google.com/store/apps/details?id=com.subhaworld.clearbill';

  static const List<Map<String, String>> indianStates = [
    {'code': '01', 'name': 'Jammu & Kashmir'},
    {'code': '02', 'name': 'Himachal Pradesh'},
    {'code': '03', 'name': 'Punjab'},
    {'code': '04', 'name': 'Chandigarh'},
    {'code': '05', 'name': 'Uttarakhand'},
    {'code': '06', 'name': 'Haryana'},
    {'code': '07', 'name': 'Delhi'},
    {'code': '08', 'name': 'Rajasthan'},
    {'code': '09', 'name': 'Uttar Pradesh'},
    {'code': '10', 'name': 'Bihar'},
    {'code': '11', 'name': 'Sikkim'},
    {'code': '12', 'name': 'Arunachal Pradesh'},
    {'code': '13', 'name': 'Nagaland'},
    {'code': '14', 'name': 'Manipur'},
    {'code': '15', 'name': 'Mizoram'},
    {'code': '16', 'name': 'Tripura'},
    {'code': '17', 'name': 'Meghalaya'},
    {'code': '18', 'name': 'Assam'},
    {'code': '19', 'name': 'West Bengal'},
    {'code': '20', 'name': 'Jharkhand'},
    {'code': '21', 'name': 'Odisha'},
    {'code': '22', 'name': 'Chhattisgarh'},
    {'code': '23', 'name': 'Madhya Pradesh'},
    {'code': '24', 'name': 'Gujarat'},
    {'code': '27', 'name': 'Maharashtra'},
    {'code': '29', 'name': 'Karnataka'},
    {'code': '30', 'name': 'Goa'},
    {'code': '32', 'name': 'Kerala'},
    {'code': '33', 'name': 'Tamil Nadu'},
    {'code': '36', 'name': 'Telangana'},
    {'code': '37', 'name': 'Andhra Pradesh'},
  ];
}
